
version: "3"

services:
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    command: --server-id=1 --log-bin=mysql-bin --binlog-format=row
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: replication_user
      MYSQL_PASSWORD: admin
    ports:
      "3010:3306"
  volumes:
    ./estructura.sql:/docker-entrypoint-initdb.d/estructura.sql,


  mysql-slave:
    image: mysql:8.0
    container_name: mysql-slave1
    depends_on:    
      mysql-master
  command: --server-id=2 --log-bin=mysql-bin --binlog-format=row
  environment:
    MYSQL_ROOT_PASSWORD: admin
    MYSQL_DATABASE: mydatabase
    MYSQL_USER: replication_user
    MYSQL_PASSWORD: admin
  ports:
    "3311:3306"


  mysql-slave2:
    image: mysql:8.0
    container_name: mysql-slave2
    depends_on: 
      mysql-master
  command: --server-id=3 --log-bin=mysql-bin --binlog-format=row
  environment:
    MYSQL_ROOT_PASSWORD: admin
    MYSQL_DATABASE: mydatabase
    MYSQL_USER: replication_user
    MYSQL_PASSWORD: admin
  ports:
    "3314:3306"