name: Deploy MySQL Master-Slave with CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Desplegar a GCP vía SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd /home/${{ secrets.GCP_USER }}/proyecto
            echo " Pull de código..."
            git pull origin main

            echo " Reiniciando contenedores..."
            docker compose down || true
            docker compose up -d --build

            echo " Restaurando estructura de base de datos..."
            docker exec -i mysql-master mysql -uroot -padmin mydatabase < estructura.sql

            echo " Configurando replicación..."
            bash scripts/replicate.sh

            echo " CI/CD completado."


