name: Respaldo y envío a contenedor real

on:
  workflow_dispatch:

jobs:
  backup_and_send:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: mydatabase
        ports:
          - 3306:3306

    steps:
    - name: Instalar MySQL Client y SSH
      run: sudo apt-get update && sudo apt-get install -y mysql-client openssh-client

    - name: Esperar MySQL
      run: |
        for i in {1..30}; do
          if mysqladmin ping -h 127.0.0.1 -P 3306 -uroot -padmin --silent; then break; fi
          sleep 2
        done

    - name: Crear tabla ejemplo y poblarla
      run: |
        echo "CREATE TABLE IF NOT EXISTS prueba (id INT PRIMARY KEY, nombre VARCHAR(50)); INSERT IGNORE INTO prueba VALUES (1, 'Erik');" > escolar.sql
        mysql -h 127.0.0.1 -P 3306 -uroot -padmin mydatabase < escolar.sql

    - name: Generar respaldo
      run: |
        mkdir -p backup
        mysqldump -h 127.0.0.1 -P 3306 -uroot -padmin mydatabase > backup/escolar_backup.sql

    - name: Enviar respaldo a tu máquina local (contenedor real)
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: "backup/escolar_backup.sql"
        target: "/home/${{ secrets.SSH_USERNAME }}/"
