# .github/workflows/backup.yml
name: Respaldo de base de datos

on:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Instalar cliente MySQL
      run: sudo apt-get update && sudo apt-get install -y mysql-client

    - name: Esperar conexión a MySQL en el puerto 3010
      run: |
        for i in {1..30}; do
          if mysqladmin ping -h 127.0.0.1 -P 3010 -uroot -padmin --silent; then
            echo "MySQL está listo"
            break
          fi
          echo "Esperando MySQL..."
          sleep 2
        done

    - name: Crear carpeta y realizar respaldo
      run: |
        mkdir -p backup
        mysqldump -h 127.0.0.1 -P 3010 -uroot -padmin mydatabase > backup/escolar_backup.sql

    - name: Comprimir respaldo
      run: tar -czf escolar_backup.tar.gz -C backup escolar_backup.sql

    - name: Subir archivo como artifact
      uses: actions/upload-artifact@v4
      with:
        name: respaldo-escolar
        path: escolar_backup.tar.gz
