name: Restauración de base de datos

on:
  workflow_dispatch:

jobs:
  restore:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: mydatabase
        ports:
          - 3306:3306

    steps:
    - name: Instalar cliente MySQL
      run: sudo apt-get update && sudo apt-get install -y mysql-client

    - name: Esperar MySQL
      run: |
        for i in {1..30}; do
          if mysqladmin ping -h 127.0.0.1 -P 3306 -uroot -padmin --silent; then break; fi
          sleep 2
        done

    - name: Descargar backup (artifact)
      uses: actions/download-artifact@v4
      with:
        name: respaldo-escolar
        path: backup

    - name: Descomprimir backup
      run: tar -xzf backup/escolar_backup.tar.gz -C backup

    - name: Restaurar base de datos
      run: mysql -h 127.0.0.1 -P 3306 -uroot -padmin mydatabase < backup/escolar_backup.sql

    - name: Verificar restauración
      run: mysql -h 127.0.0.1 -P 3306 -uroot -padmin -e "SELECT * FROM prueba;" mydatabase
