name: Respaldo de base de datos

on:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: mydatabase
        ports:
          - 3306:3306

    steps:
    - name: Instalar cliente MySQL
      run: sudo apt-get update && sudo apt-get install -y mysql-client

    - name: Esperar MySQL
      run: |
        for i in {1..30}; do
          if mysqladmin ping -h 127.0.0.1 -P 3306 -uroot -padmin --silent; then break; fi
          sleep 2
        done

    - name: Crear datos de ejemplo
      run: |
        echo "CREATE TABLE IF NOT EXISTS prueba (id INT PRIMARY KEY, nombre VARCHAR(50)); INSERT IGNORE INTO prueba VALUES (1, 'Erik');" > escolar.sql
        mysql -h 127.0.0.1 -P 3306 -uroot -padmin mydatabase < escolar.sql

    - name: Hacer respaldo SQL
      run: |
        mkdir -p backup
        mysqldump -h 127.0.0.1 -P 3306 -uroot -padmin mydatabase > backup/escolar_backup.sql

    - name: Subir como artifact
      uses: actions/upload-artifact@v3
      with:
        name: respaldo-escolar
        path: backup/escolar_backup.sql
