# .github/workflows/restaurar.yml
name: Restauraci칩n de base de datos

on:
  workflow_dispatch:

jobs:
  restore:
    runs-on: ubuntu-latest

    steps:
    - name: Instalar cliente MySQL
      run: sudo apt-get update && sudo apt-get install -y mysql-client

    - name: Esperar conexi칩n a MySQL en el puerto 3010
      run: |
        for i in {1..30}; do
          if mysqladmin ping -h 127.0.0.1 -P 3010 -uroot -padmin --silent; then
            echo "MySQL est치 listo"
            break
          fi
          echo "Esperando MySQL..."
          sleep 2
        done

    - name: Descargar artifact
      uses: actions/download-artifact@v4
      with:
        name: respaldo-escolar
        path: backup

    - name: Descomprimir respaldo
      run: tar -xzf backup/escolar_backup.tar.gz -C backup

    - name: Restaurar la base de datos
      run: mysql -h 127.0.0.1 -P 3010 -uroot -padmin mydatabase < backup/escolar_backup.sql

    - name: Verificar restauraci칩n
      run: mysql -h 127.0.0.1 -P 3010 -uroot -padmin -e "SHOW TABLES FROM mydatabase;"
