name: Restaurar base de datos desde backup

on:
  workflow_dispatch:

jobs:
  restore:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: mydatabase
        ports:
          - 3306:3306

    steps:
    - name: Descargar artefacto del respaldo
      uses: actions/download-artifact@v4
      with:
        name: respaldo-escolar
        path: restore/

    - name: Instalar cliente MySQL
      run: |
        sudo apt-get update && sudo apt-get install -y mysql-client

    - name: Esperar a que MySQL esté listo
      run: |
        for i in {1..30}; do
          if mysqladmin ping -h 127.0.0.1 -P 3306 -uroot -padmin --silent; then
            echo "MySQL listo"
            break
          fi
          echo "Esperando MySQL..."
          sleep 2
        done

    - name: Restaurar respaldo en MySQL
      run: |
        mysql -h 127.0.0.1 -P 3306 -uroot -padmin mydatabase < restore/escolar_backup.sql
