name: Restauración desde respaldo manual

on:
  workflow_dispatch:

jobs:
  restore:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: mydatabase
        ports:
          - 3306:3306

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Instalar cliente de MySQL
      run: sudo apt-get update && sudo apt-get install -y mysql-client

    - name: Esperar a que MySQL esté listo
      run: |
        for i in {1..30}; do
          if mysqladmin ping -h 127.0.0.1 -P 3306 -uroot -padmin --silent; then
            echo "MySQL está listo"
            break
          fi
          echo "Esperando..."
          sleep 2
        done

    - name: Descomprimir respaldo
      run: tar -xzf backup/escolar_backup.tar.gz -C backup

    - name: Restaurar base de datos
      run: mysql -h 127.0.0.1 -P 3306 -uroot -padmin mydatabase < backup/escolar_backup.sql

    - name: Verificar datos restaurados
      run: mysql -h 127.0.0.1 -P 3306 -uroot -padmin -e "SELECT * FROM mydatabase.prueba;"
