name: Prueba completa de backup y restauración

on:
  workflow_dispatch:

jobs:
  backup_restore:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: mydatabase
        ports:
          - 3306:3306

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Instalar cliente MySQL
      run: sudo apt-get update && sudo apt-get install -y mysql-client

    - name: Esperar a que MySQL esté listo
      run: |
        for i in {1..30}; do
          if mysqladmin ping -h 127.0.0.1 -P 3306 -uroot -padmin --silent; then
            echo "MySQL está listo"
            break
          fi
          echo "Esperando..."
          sleep 2
        done

    - name: Crear tabla de prueba
      run: |
        echo "CREATE TABLE prueba (id INT PRIMARY KEY, nombre VARCHAR(50)); INSERT INTO prueba VALUES (1, 'Erik');" > escolar.sql
        mysql -h 127.0.0.1 -P 3306 -uroot -padmin mydatabase < escolar.sql

    - name: Realizar respaldo
      run: |
        mkdir -p backup
        mysqldump -h 127.0.0.1 -P 3306 -uroot -padmin mydatabase > backup/escolar_backup.sql

    - name: Eliminar tabla para simular restauración
      run: |
        echo "DROP TABLE prueba;" | mysql -h 127.0.0.1 -P 3306 -uroot -padmin mydatabase

    - name: Restaurar desde respaldo
      run: |
        mysql -h 127.0.0.1 -P 3306 -uroot -padmin mydatabase < backup/escolar_backup.sql

    - name: Comprobar restauración
      run: |
        mysql -h 127.0.0.1 -P 3306 -uroot -padmin -e "SELECT * FROM mydatabase.prueba;"

