name: Backup MySQL Escolar

on:
  schedule:
    - cron: '0 3 * * *' # Todos los días a las 3 AM UTC
  workflow_dispatch:      # Permite ejecutarlo manualmente desde GitHub

jobs:
  backup:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: mydatabase
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout repositorio
      uses: actions/checkout@v3

    - name: Instalar cliente MySQL
      run: sudo apt-get update && sudo apt-get install -y mysql-client

    - name: Esperar base de datos
      run: sleep 20

    - name: Crear respaldo escolar.sql
      run: |
        mkdir -p backup
        mysqldump -h 127.0.0.1 -P 3306 -uroot -padmin mydatabase > backup/escolar_backup.sql

    - name: Guardar respaldo como artefacto
      uses: actions/upload-artifact@v4
      with:
        name: respaldo-escolar
        path: backup/escolar_backup.sql
